default:
  - noodle
  - treat box
  - potato chips
  - detergent
  - cup
  - lunch box
  - dice
  - light bulb box
  - block box

tidyup_item_list:
  - noodle # cup, white cup
  - treat box # green box
  - {color} box
  - potato chips ### orange cup
  - detergent # yellow bottle
  - cup ### blue cup
  - lunch box ### cup, case, round case
  - dice ### cup, white block
  - light bulb box # black box, black block###
  - block box # treat box, box, block###
tidyup_